/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/model.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mob_1.geometry} material={nodes.mob_1.material} position={[2.986, 0.241, 0.997]} />
      <mesh geometry={nodes.spear_1.geometry} material={nodes.spear_1.material} position={[1, 0.802, 1]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.healthBox.geometry} material={nodes.healthBox.material} position={[5.105, 0.905, 0.96]}>
        <mesh geometry={nodes.health_1.geometry} material={nodes.health_1.material} position={[-0.004, 0.052, 0.043]} rotation={[0.585, 0, 0]} />
      </mesh>
      <mesh geometry={nodes.tree.geometry} material={nodes.tree.material} position={[3, 0.122, 2.877]} />
      <mesh geometry={nodes.dummy_1.geometry} material={nodes.dummy_1.material} position={[-1.086, 0.245, 1.002]} />
      <mesh geometry={nodes.barier.geometry} material={nodes.barier.material} position={[-1.922, 0, 3.109]} rotation={[-Math.PI, 1.484, -Math.PI]} />
      <mesh geometry={nodes.wall_1.geometry} material={nodes.wall_1.material} position={[13, -0.099, 0.982]} />
      <mesh geometry={nodes.dground.geometry} material={nodes.dground.material} />
      <mesh geometry={nodes.doorTorch.geometry} material={nodes.doorTorch.material} position={[21.102, -0.065, 28.368]} />
      <mesh geometry={nodes.exitDoor.geometry} material={nodes.exitDoor.material} position={[15, 0, 31]} />
    </group>
  )
}

useGLTF.preload('/model.glb')
