/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/model.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/model.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="mob_1" geometry={nodes.mob_1.geometry} material={nodes.mob_1.material} position={[2.986, 0.241, 0.997]} />
        <mesh name="healthBox" geometry={nodes.healthBox.geometry} material={nodes.healthBox.material} position={[5.105, 0.905, 0.96]}>
          <mesh name="health_1" geometry={nodes.health_1.geometry} material={nodes.health_1.material} position={[-0.004, 0.052, 0.043]} rotation={[0.585, 0, 0]} />
        </mesh>
        <mesh name="tree" geometry={nodes.tree.geometry} material={nodes.tree.material} position={[3, 0.122, 2.877]} />
        <mesh name="dummy_1" geometry={nodes.dummy_1.geometry} material={nodes.dummy_1.material} position={[-1.086, 0.245, 1.002]} />
        <mesh name="barier" geometry={nodes.barier.geometry} material={nodes.barier.material} position={[-1.922, 0, 3.109]} rotation={[-Math.PI, 1.484, -Math.PI]} />
        <mesh name="wall_1" geometry={nodes.wall_1.geometry} material={nodes.wall_1.material} position={[13, -0.099, 0.982]} />
        <mesh name="dground" geometry={nodes.dground.geometry} material={nodes.dground.material} />
        <mesh name="doorTorch" geometry={nodes.doorTorch.geometry} material={nodes.doorTorch.material} position={[21.102, -0.065, 28.368]} />
        <mesh name="exitDoor" geometry={nodes.exitDoor.geometry} material={nodes.exitDoor.material} position={[15, 0, 31]} />
        <mesh name="door_1" geometry={nodes.door_1.geometry} material={nodes.door_1.material} position={[15, 0, 1]}>
          <mesh name="door_1_face1" geometry={nodes.door_1_face1.geometry} material={nodes.door_1_face1.material} position={[0, 1.018, -0.746]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.862, 1, 0.761]} />
          <mesh name="door_1_face2" geometry={nodes.door_1_face2.geometry} material={nodes.door_1_face2.material} position={[0.752, 1.018, 0.005]} rotation={[0, 0, -Math.PI / 2]} scale={[0.862, 1, 0.75]} />
          <mesh name="door_1_face3" geometry={nodes.door_1_face3.geometry} material={nodes.door_1_face3.material} position={[-0.748, 1.018, 0.005]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={[0.862, 1, 0.75]} />
          <mesh name="door_1_face4" geometry={nodes.door_1_face4.geometry} material={nodes.door_1_face4.material} position={[0, 1.018, 0.754]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.862, 1, 0.761]} />
        </mesh>
        <mesh name="spear_2" geometry={nodes.spear_2.geometry} material={nodes.spear_2.material} position={[7.02, 0.356, 1.084]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh name="spear_2_head" geometry={nodes.spear_2_head.geometry} material={nodes.spear_2_head.material} position={[0, 0.79, 0.001]} scale={1.227} />
        </mesh>
        <mesh name="spear_1" geometry={nodes.spear_1.geometry} material={nodes.spear_1.material} position={[1, 1.775, -0.224]} rotation={[0.842, 0, 0]} />
        <mesh name="planeGround" geometry={nodes.planeGround.geometry} material={nodes.planeGround.material} position={[1, 0, -2]} />
        <mesh name="nArrow" geometry={nodes.nArrow.geometry} material={nodes.nArrow.material} position={[1.166, 1.588, 1.595]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="nWall" geometry={nodes.nWall.geometry} material={nodes.nWall.material} position={[5, 0, -2]} />
        <mesh name="ndecor1" geometry={nodes.ndecor1.geometry} material={nodes.ndecor1.material} position={[7.1, 0.002, -2]} />
        <mesh name="ndecor2" geometry={nodes.ndecor2.geometry} material={nodes.ndecor2.material} position={[3, 0.02, -2]} />
        <mesh name="key_1" geometry={nodes.key_1.geometry} material={nodes.key_1.material} position={[13.002, 0.83, -2]} />
        <mesh name="nmob1" geometry={nodes.nmob1.geometry} material={nodes.nmob1.material} position={[11, 1.002, -2]}>
          <mesh name="nmob1_hand_l" geometry={nodes.nmob1_hand_l.geometry} material={nodes.nmob1_hand_l.material} position={[0.639, -0.473, -0.066]} />
          <mesh name="nmob1_hand_r" geometry={nodes.nmob1_hand_r.geometry} material={nodes.nmob1_hand_r.material} position={[-0.639, -0.494, 0]} />
          <mesh name="nmob1head" geometry={nodes.nmob1head.geometry} material={nodes.nmob1head.material} />
          <mesh name="nmob1horn" geometry={nodes.nmob1horn.geometry} material={nodes.nmob1horn.material} />
        </mesh>
        <mesh name="crate_1" geometry={nodes.crate_1.geometry} material={nodes.crate_1.material} position={[9.005, 1.002, -2]} />
        <mesh name="nbarrier" geometry={nodes.nbarrier.geometry} material={nodes.nbarrier.material} position={[14.992, 0.001, -2]}>
          <mesh name="nbarrierplane" geometry={nodes.nbarrierplane.geometry} material={nodes.nbarrierplane.material} position={[0.008, 0.912, 0]} rotation={[Math.PI / 2, 0, 0]} />
        </mesh>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[28, 1, -5]} />
        <mesh name="pcoin_1" geometry={nodes.pcoin_1.geometry} material={nodes.pcoin_1.material} position={[32, 1.005, -5]} />
        <mesh name="pdecor_1" geometry={nodes.pdecor_1.geometry} material={nodes.pdecor_1.material} position={[36, 0, -5]}>
          <mesh name="pdecor_1_leaf" geometry={nodes.pdecor_1_leaf.geometry} material={nodes.pdecor_1_leaf.material} />
        </mesh>
        <mesh name="pheal_1" geometry={nodes.pheal_1.geometry} material={nodes.pheal_1.material} position={[38, 0.146, -5]} />
        <mesh name="playerBullet_1" geometry={nodes.playerBullet_1.geometry} material={nodes.playerBullet_1.material} position={[22, 0, -5]} />
        <mesh name="playerBullet_2" geometry={nodes.playerBullet_2.geometry} material={nodes.playerBullet_2.material} position={[26, 1.005, -5]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="playerBullet_3" geometry={nodes.playerBullet_3.geometry} material={nodes.playerBullet_3.material} position={[40, 1.046, -5]} />
        <mesh name="pmob_1" geometry={nodes.pmob_1.geometry} material={nodes.pmob_1.material} position={[34, 0.007, -3]} />
        <mesh name="pmob_bullet" geometry={nodes.pmob_bullet.geometry} material={nodes.pmob_bullet.material} position={[30, 1.005, -5]} />
        <mesh name="pmob_0" geometry={nodes.pmob_0.geometry} material={nodes.pmob_0.material} position={[24, 0.005, -5]} />
        <mesh name="pwall_2" geometry={nodes.pwall_2.geometry} material={nodes.pwall_2.material} position={[42, -0.019, -5]} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
